### ISSUE TITLE
Sample app crashes

### ISSUE THREAD

**Issue by dmytrodanylyk** [asyl/ArcAnimator#2]
[Sample](https://github.com/asyl/ArcAnimator/releases) app crashes when animation is completed.

```
java.lang.IllegalArgumentException: View must be inside RevealFrameLayout or RevealLinearLayout.
            at io.codetail.animation.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:52)
            at io.codetail.arcsample.TransitionLoopFragment.appearBluePair(TransitionLoopFragment.java:95)
            at io.codetail.arcsample.TransitionLoopFragment$1$1.onAnimationEnd(TransitionLoopFragment.java:82)
            at com.nineoldandroids.animation.ValueAnimator.endAnimation(ValueAnimator.java:1034)
            at com.nineoldandroids.animation.ValueAnimator.access$900(ValueAnimator.java:43)
            at com.nineoldandroids.animation.ValueAnimator$AnimationHandler.handleMessage(ValueAnimator.java:669)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by asyl** [comment]
I haven't update sample app. Sample app doen't work properly on all versions. However, this lib does. I will try to rewrite sample for all versions.

**Comment by ravshanoff** [comment]
Asyl just close this issue.
